### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by 3735943886** [2odkc/zigbang_doorlock_homekit#1]
Instead of requesting the entire logs, how about trying `/openhome/v20/doorlockctrl/membersdoorlocklist` with providing battery information as well?

method: `GET`
data: `createDate=20240308120000`, `favoriteYn=A`, `hashData=(empty)`, `memberId=00000000-0000-0000-0000-000000000000`
response: `JSON`

**Comment by 3735943886** [comment]
In my case, `get_log` produces approximately 250KiB of ingress traffic per request, whereas `openhome/v20/doorlockctrl/membersdoorlocklist` consumes approximately 4KiB per request.

Here’s the code snippet:
```
url = 'https://iot.samsung-ihp.com:8088/openhome/v20/doorlockctrl/membersdoorlocklist?createDate={}&favoriteYn=A&hashData=&memberId={}'.format(datetime.now().strftime("%Y%m%d%H%M%S"), d.member_id)
res = d.get(url, headers).json()
doorlock_status = res['doorlockVOList'][0]['doorlockStatusVO']['locked']
```

This snippet retrieves the current doorlock status as a boolean from the JSON response.

**Comment by kunho-park** [comment]
I have incorporated the suggestions.
